core:
- any:
  - changed-files:
    - any-glob-to-any-file: ['src']

tests:
- any:
  - changed-files:
    - any-glob-to-any-file: ['tests']

docs:
- any:
  - changed-files:
    - any-glob-to-any-file: ['docs']

devex:
- any:
  - changed-files:
    - any-glob-to-any-file: ['.devcontainer', '.github']

agents:
- any:
  - changed-files:
    - any-glob-to-any-file: ['AGENTS.md']

contributing:
- any:
  - changed-files:
    - any-glob-to-any-file: ['CONTRIBUTING.md']