# StrataRegula Test Configuration
# Test intelligent completion by typing patterns like:
# - prod. (environment completion)
# - web. (service completion) 
# - database: (config type completion)

service_times:
  prod.frontend.response: 200
  prod.backend.timeout: 30
  dev.api.retry: 3

resource_limits:
  web.*.cpu: 80
  api.*.memory: 512

traffic_routing:
  frontend.*.route: "/api/v1"
  backend.*.endpoint: ":8080"

# Test completion here - try typing "prod." or "web." or "database:"
test_completions:
  # Type patterns here to test LSP completions

environments:
  production:
    database:
      host: "prod-db.example.com"
      port: 5432
    cache:
      host: "prod-cache.example.com"
  
  development:
    database:
      host: "dev-db.example.com"
      port: 5432
    cache:
      host: "dev-cache.example.com"