name: Secret Audit
on:
  pull_request:
    paths:
      - '.devcontainer/**'
      - '**/.env*'
      - '**/config.*'
      - '**/*.config.*'
      - '**/settings.*'
  workflow_dispatch:

jobs:
  secret-detection:
    name: Detect secrets in configuration files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install PowerShell
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Run secret detection on .devcontainer
        shell: pwsh
        run: |
          chmod +x ./secret-audit.ps1
          ./secret-audit.ps1 -ScanPath ".devcontainer" -Verbose

      - name: Run secret detection on configuration files
        shell: pwsh
        run: |
          # Scan additional high-risk paths
          $paths = @('.env*', 'config', 'configs', '.vscode')
          foreach ($path in $paths) {
            if (Test-Path $path) {
              Write-Host "Scanning path: $path"
              ./secret-audit.ps1 -ScanPath $path -Verbose
            }
          }

      - name: Security summary
        if: always()
        run: |
          echo "🛡️ Secret detection scan completed"
          echo "📋 Scanned paths: .devcontainer, config files, environment files"
          echo "🔍 Detected patterns: GitHub tokens, AWS keys, OpenAI keys, JWT tokens, private keys"