name: docs-linkcheck
on:
  pull_request:
    paths: ["**/*.md"]
  workflow_dispatch:
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-mail
            --timeout 20
            **/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}