name: pr-size
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add size label
        uses: pascalgn/size-label-action@v0.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "XS": 0,
              "S": 50,
              "M": 200,
              "L": 500,
              "XL": 1000,
              "XXL": 2000
            }