name: Publish VS Code Extension

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write    # GitHub Release作成に必須

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check version consistency (tag vs package.json)
        run: |
          TAG="${GITHUB_REF_NAME}"
          PKG="$(jq -r .version package.json)"
          echo "TAG=${TAG}  PKG=v${PKG}"
          [[ "${TAG#v}" == "${PKG}" ]] || { echo "❌ Version mismatch: tag ${TAG} vs package.json ${PKG}"; exit 1; }
          echo "✅ Version check passed: ${TAG} matches package.json"
      
      - name: Check CHANGELOG has version entry
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          grep -E "^##? +\[?${VERSION}\]?" CHANGELOG.md \
            || { echo "❌ CHANGELOG.md missing section for ${VERSION}"; exit 1; }
          echo "✅ CHANGELOG check passed: Found entry for ${VERSION}"

  publish:
    needs: preflight
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci
        
      - name: Compile TypeScript
        run: npm run build
        
      - name: Install vsce
        run: npm install -g @vscode/vsce
        
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        
      - name: Set version in package.json
        run: |
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            pkg.version = '${{ steps.version.outputs.VERSION }}';
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          
      - name: Package extension
        run: vsce package
        
      - name: Publish to VS Code Marketplace
        run: npm run publish
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
